apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.vector.name }}
  name: {{ .Values.vector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: prom-remwrite
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: prom-agg
      port: 9042
      protocol: TCP
      targetPort: 9042
    - name: prom-metrics
      port: 9598
      protocol: TCP
      targetPort: 9598
    - name: graphql
      port: 8686
      protocol: TCP
      targetPort: 8686
    - name: vector-to-vector
      port: 6000
      protocol: TCP
      targetPort: 6000

  selector:
    app: {{ .Values.vector.name }}
  sessionAffinity: None
  type: ClusterIP
