apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: {{ .Values.vector.name }}
    # todo labels
rules:
    - apiGroups: [""]
      resources: ["secrets", "configmaps", "namespaces"]
      verbs: ["get", "watch", "list"]
    
 
