apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: {{ .Values.vector.name }}
    # todo labels
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ .Values.vector.name }}
subjects: 
    - kind: ServiceAccount
      name: {{ .Values.vector.name }}
      namespace: {{ .Release.Namespace }}
