apiVersion: v1
kind: Secret
metadata:
  name: usage-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  USAGE_BUCKET_ACCESS_ID: {{ .Values.ENV_AWS_ACCESS_KEY_ID }}
  USAGE_BUCKET_SECRET: {{ .Values.ENV_AWS_SECRET_ACCESS_KEY }}
