apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  namespace: {{ .Release.Namespace }}
  labels:
    app: fluent-bit
spec:
  ports:
    - name: nginx
      port: 514
      protocol: UDP
      targetPort: 1514
    - name: other
      port: 5170
      protocol: TCP
      targetPort: 5170
  selector:
    app: fluent-bit
