apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cmd-processor
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs: ["get", "list", "patch"]
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs: ["get", "update"]
- apiGroups:
  - ""
  resources:
  - services
  verbs: ["get", "create" , "list", "update", "delete"]
