# this secret is the crypto guts of the secure connect bundle
# not explicitly used in k8s right now, but useful to have around if we need to
# rotate the server or client certs
apiVersion: v1
kind: Secret
metadata:
  name: client-cert
type: Opaque
data:
  crt: {{ .Values.clientCert }}
  key: {{ .Values.clientKey }}
  ca: {{ .Values.caCert }}
  caKey: {{ .Values.caKey }}
