apiVersion: v1
kind: ServiceAccount
metadata:
  name: cmd-processor
  labels:
    {{- include "cmd-processor.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
