apiVersion: v1
kind: Service
metadata:
  name: cmd-processor
  labels:
    {{- include "cmd-processor.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "cmd-processor.selectorLabels" . | nindent 4 }}
  ports:
  - name: xds
    port: 7777
    protocol: TCP
  - name: egresstracking
    port: 5140
    protocol: UDP
  - name: metadata
    port: 30443
    protocol: TCP
  - name: migratormetadata
    port: 35443
    protocol: TCP
  - name: dsemetadata
    port: 36443
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: stargate-seeds
  labels:
    app: stargate
spec:
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: stargate-seeds
  labels:
    app: stargate
  name: stargate-seeds
