apiVersion: v1
kind: Secret
metadata:
  name: sqs-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.sqsAWSAccessKeyID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.sqsAWSSecretAccessKey | b64enc }}
