apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: {{ .Values.vector.name }}
    namespace: {{ .Release.Namespace }}
    # todo labels
rules:
    - apiGroups: [""]
      resources: ["secrets", "configmaps"]
      verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
    
 